# Site settings
title: FraguaFisioterapia | Tradición y Experiencia en terapia manual
description: "FraguaFisioterapia, Tradición y Experiencia en terapia manual. Conoce nuestras terapias, especializado en Fisioterapia y Rehabilitación."
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://www.fraguafisioterapia.es" # the name of your domain
#url: "https://wwwfraguafisioterapiaes.000webhostapp.com" # the name of your domain
url: "http://www.fraguafisioterapia.es" # the name of your domain
logo_url: /img/logo.jpg

# Hero
hero:
    hero_img: /img/ppal_masaje.jpg
    hero_title: Fragua Fisioterapia
    hero_description: Tradición y Experiencia en Terapia Manual.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    emergency:
    phone: "657 05 36 90"
    email: fraguafisioterapia@gmail.com
    address: C/ Valdemoro 11 Local 2,<br> 28914 Leganés (Arroyo Culebro), Madrid

    renfe: Parque Polvoranca, Línea C5 (Mostoles el Soto- Humanes)
    bus: 482, Madrid (Aluche) - Leganés (Arroyo Culebro)
# Opening hours
monday_friday: 18:15 – 21:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Valdemoro 11 Local 2, 28914 Leganés (Arroyo Culebro), Madrid, España
    address_details: svg/min/logo.svg
    gps: C/ Valdemoro esquina C/ Alcalde Vicente de la Barrera Cano
# Social settings
facebook: https://www.facebook.com/Fragua-Fisioterapia-1479828245652282/
twitter:
instagram:
youtube:
skype:
feed: no

# Footer
copyright: © 2019 FraguaFisioterapia - Todos los derechos reservados
legal:
  politica: "De conformidad con el vigente Reglamento (UE) 2016/679, informamos que los datos de carácter personal de los Usuarios del sitio web se tratarán para la actividad de tratamiento de citas, información y demás cuestiones relacionadas con la Fisioterapia. Dicho tratamiento de sus datos estará amparado en su propio consentimiento. Al pulsar el botón 'ENVIAR', el Usuario consiente el tratamiento de sus datos por parte de la empresa.
Asimismo, le informamos que, salvo obligación legal o consentimiento expreso por su parte, no cederemos sus datos a terceros.
Igualmente, se informa al Usuario que en cualquier momento puede ejercitar los derechos de acceso, rectificación o supresión de datos, así como disponer de otros derechos reconocidos en el presente documento y regulados en el Reglamento (UE) 2016/679, notificándolo a Miguel Angel Fragua Díaz. C/ Valdemoro 11. 28914. Leganés. Email: fraguafisioterapia@gmail.com"
  aviso: /img/aviso.jpg
  cookies: "La normativa en materia de publicidad y gestión del consentimiento para la utilización de <b>cookies, píxeles u otros elementos de almacenamiento de información </b> conlleva
 la obligación a toda <u>pagina web, blog o tienda online </u> de adaptarse a la <b>normativa sobre cookies de la LSSI-CE</b>. El objetivo es ofrecer al usuario toda la información sobre <b>qué tipos de datos se están almacenando y qué tipos de cookies se están utilizando para
 conseguirlo.</b>
<br><br>La descarga de este tipo de elementos suponen la capacidad para recopilar <b>información de la actividad del usuario</b> y tiene implicaciones en relación a tu <b>privacidad</b>.
Por ello, la normativa impone la <b>obligación de obtener el consentimiento informado de los usuarios</b> para aceptar la utilización de cookies en cualquier sitio web.
<br><br>
<b>Consentimiento y autorización para el uso de cookies</b>: Al acceder a este sitio web por primera vez, <b>verás una barra </b>(en la parte inferior de la web) donde se te informa de la utilización de
las cookies y que te permite, aparte de consultar nuestra política de cookies (y otras políticas de privacidad), elegir si aceptar uso de cookies de este sitio web. Si simplemente haces <b>click en “Acepto”, consientes la utilización de cookies,</b> por lo que se
entenderá que has consentido nuestra política de cookies y, por tanto, la aceptación para la instalación de las mismas en tu equipo o
dispositivo (excepto en la medida que haya modificado la configuración de tu navegador para rechazar la utilización de las mismas).
<br><br>
<b>Cookies propias y de terceros que utiliza este sitio web</b>: Este sitio web utiliza el <b>servicio externo de Google Analytics</b> para recopilar información de la actividad del usuario, para así poder analizarla y
mejorar los contenidos y la experiencia de usuario.
<br>
Adicionalmente, este sitio web emplea una <b>cookie propia</b>, para poder recordar tu preferencia en la configuración de privacidad. La aceptación de esta cookie hace que no tengas que aceptar el uso de cookies cada vez que accedas durante un <b>máximo de 30 días</b>
<br>
El acceso a este sitio web implica que se puedan instalar estas cookies.
<br><br>
<b>Cómo desactivar las cookies desde tu navegador</b>: Todos los navegadores permiten hacer cambios que <b>permiten desactivar la configuración de las cookies</b>. Estos ajustes se encuentran ubicados
            en las “opciones” o “preferencias” del <b>menú del navegador</b>. A continuación te dejo enlaces con instrucciones para diferentes navegadores
            donde verás <b>cómo deshabilitar las cookies</b>. No obstante, recuerda que inhabilitar cookies implica perder funcionalidad en muchos sitios web.
"
# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: "UA-114027986-1"
google_verification: "q3NJEdif2X7XP0df9EmHY9cfldOk8LINmioV8YKGHpA"
